# -*- coding: utf-8 -*-
"""nontrivial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MuKfKQ-07m2vR8Zthrtqvrj6k5UErNzd
"""

!pip install scikit-learn pandas numpy joblib --quiet

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import joblib

from google.colab import drive
drive.mount('/content/drive')

fake = pd.read_csv('/content/drive/MyDrive/archive/Fake.csv')
real = pd.read_csv('/content/drive/MyDrive/archive/True.csv')

fake['label'] = 1
real['label'] = 0

df = pd.concat([fake, real], ignore_index=True)

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

X = df['text']
y = df['label']

vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)
X_vect = vectorizer.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_vect, y, test_size=0.2, random_state=42)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

joblib.dump(model, "fake_news_model.joblib")
joblib.dump(vectorizer, "tfidf_vectorizer.joblib")
print("\nModel and vectorizer saved successfully.")

